[package]

name = "kmeans"
version = "0.1.2"
authors = [ "Andrea Ferretti <ferrettiandrea@gmail.com>" ]


[lib]
name = "kmeans"
path = "src/lib.rs"

[[bin]]
name = "kmeans_bin"
path = "src/main.rs"

[dependencies]
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"

time = "*"
